<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Notification.Application\Notification.Application.csproj" />
    <ProjectReference Include="..\Notification.Domain\Notification.Domain.csproj" />
    <ProjectReference Include="..\Notification.Infrastructure\Notification.Infrastructure.csproj" />
    <ProjectReference Include="..\Notification.Shared\Notification.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Shared.Events">
      <HintPath>..\..\RabbitMQ\EventDrivenServices\Shared.Events\bin\Debug\net8.0\Shared.Events.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
